<a href="https://colab.research.google.com/github/victorrp1502/grupo1_caixaverso/blob/Branch_Marcos/Marcos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Teste Commit

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [34]:
#df = pd.read_csv('https://drive.google.com/uc?id=1k-6AbaByg4SWF9UgrJ94p4TafHHXOmUG')
def carregar_banco_csv(caminho):
    return pd.read_csv(caminho)
    pass

In [35]:
carregar_banco_csv('https://drive.google.com/uc?id=1k-6AbaByg4SWF9UgrJ94p4TafHHXOmUG')

,job_title,experience_level,employment_type,work_models,work_year,employee_residence,salary,salary_currency,salary_in_usd,company_location,company_size
0,Data Engineer,Mid-level,Full-time,Remote,2024,United States,148100,USD,148100,United States,Medium
1,Data Engineer,Mid-level,Full-time,Remote,2024,United States,98700,USD,98700,United States,Medium
2,Data Scientist,Senior-level,Full-time,Remote,2024,United States,140032,USD,140032,United States,Medium
3,Data Scientist,Senior-level,Full-time,Remote,2024,United States,100022,USD,100022,United States,Medium
4,BI Developer,Mid-level,Full-time,On-site,2024,United States,120000,USD,120000,United States,Medium
...,...,...,...,...,...,...,...,...,...,...,...
6594,Staff Data Analyst,Entry-level,Contract,Hybrid,2020,Canada,60000,CAD,44753,Canada,Large
6595,Staff Data Analyst,Executive-level,Full-time,On-site,2020,Nigeria,15000,USD,15000,Canada,Medium
6596,Machine Learning Manager,Senior-level,Full-time,Hybrid,2020,Canada,157000,CAD,117104,Canada,Large
6597,Data Engineer,Mid-level,Full-time,Hybrid,2020,Austria,65000,EUR,74130,Austria,Large
6598,Data Scientist,Senior-level,Full-time,On-site,2020,Austria,80000,EUR,91237,Austria,Small

#3 - Onde estão as melhores oportunidades? Quais países da residência do empregado têm os maiores salários médios? Existe correlação entre país e modalidade de trabalho (remoto vs presencial)?

In [94]:
def media_salario_por_pais(df):
    return df.groupby('employee_residence')['salary_in_usd'].mean().round(2).reset_index().rename(columns={'employee_residence': 'País',
              'salary_in_usd': 'Salário Médio'}).sort_values(by='Salário Médio', ascending=False).head(10)

In [95]:
media_salario_por_pais(df)

                      País  Salário Médio
40                  Israel      417937.00
65                   Qatar      300000.00
50                Malaysia      200000.00
64             Puerto Rico      166000.00
84           United States      157780.94
56             New Zealand      151634.33
12                  Canada      140564.88
68            Saudi Arabia      134999.00
15                   China      125404.00
9   Bosnia and Herzegovina      120000.00
5                Australia      117454.62
22      Dominican Republic      110000.00
39                 Ireland      107633.90
81                 Ukraine      107571.43
75                  Sweden      105000.00
83          United Kingdom      103392.37
76             Switzerland      101659.40
29                 Germany      100453.18
43                  Jersey      100000.00
37                    Iran      100000.00

In [101]:
def media_salario_top10_por_modalidade(df):
    top10_paises = (df.groupby('employee_residence')['salary_in_usd'].mean().round(2).reset_index()
          .sort_values(by='salary_in_usd', ascending=False).head(10)['employee_residence'].tolist())

    df_filtrado = df[df['employee_residence'].isin(top10_paises)]

    return df_filtrado.groupby(['employee_residence', 'work_models'])['salary_in_usd']\
        .mean().round(2).reset_index().rename(columns={'employee_residence': 'País',
        'work_models': 'Modalidade','salary_in_usd': 'Salário Médio'}).sort_values(by=['País', 'Salário Médio'], ascending=[True, False])

In [102]:
media_salario_top10_por_modalidade(df)

                      País Modalidade  Salário Médio
0   Bosnia and Herzegovina     Hybrid      120000.00
2                   Canada    On-site      142655.21
3                   Canada     Remote      142192.41
1                   Canada     Hybrid      112649.67
4                    China     Hybrid      125404.00
5                   Israel    On-site      417937.00
6                 Malaysia     Remote      200000.00
8              New Zealand    On-site      164951.50
7              New Zealand     Hybrid      125000.00
10             Puerto Rico     Remote      167500.00
9              Puerto Rico     Hybrid      160000.00
11                   Qatar     Remote      300000.00
12            Saudi Arabia     Remote      134999.00
14           United States    On-site      159901.83
15           United States     Remote      154634.15
13           United States     Hybrid      141350.00

#6 - Porte da empresa e salário. Empresas grandes (L), médias (M) ou pequenas (S) pagam mais? A diferença é maior em algum nível de experiência específico?